### ISSUE TITLE
请问，我应该如何解析嵌套的json

### ISSUE THREAD

**Issue by HsiangCheng** [xyz347/x2struct#1]
我的同事正在使用你的库解析json，他一直坚持你的库无法解析嵌套json，并要求我将嵌套的Object转为String。但我希望数据可以按照json的标准形式进行传输，我不是C++程序员，阅读你的源码有些困难，
所以我希望得到你的帮助。

我坚持的结构：

```
{
    "errorCode": 0,
    "message": "",
    "data": {
        "timestamp": 1531710826,
        "collections": [
            {
                "temperature": 26.7,
                "mac": "ABCDEF",
                "humidity": 75.1
            },
            {
                "temperature": 25.9,
                "mac": "ABCDE2",
                "humidity": 74.6
            
        ],
        "address": "DEFAB"
    }
}
```

他所坚持的结构：

```
{
    "errorCode": 0,
    "message": "",
    "data": "{\"timestamp\": 1531710826,\"collections\": [{\"temperature\": 26.7,\"mac\": \"ABCDEF\","humidity": 75.1},{\"temperature\": 25.9,\"sensorMac\": \"ABCDE2\",\"humidity\": 74.6],\"address\": \"DEFAB\"}"
}
```

**Comment by xyz347** [comment]
支持结构体嵌套的，像你的这种需要这么来定义：
struct Collection {
    float temperature;
    std::string mac;
    float humidity;
    XTOSTRUCT(O(temperature, mac, humidity));
};

struct Data {
    int64_t timestamp;
    std::vector<Collection> collections;
    std::string address;
    XTOSTRUCT(O(timestamp, collections, address));
};

struct Info {
    int errorCode;
    std::string message;
    Data data;
    XTOSTRUCT(O(errorCode, message, data));
};

int main(int argc, char *argv[]) {
    Info in;
    in.errorCode = 0;
    in.data.timestamp = 1531710826;
    in.data.collections.resize(2);
    in.data.collections[0].temperature = 26.7;
    in.data.collections[0].mac = "ABCDEF";
    in.data.collections[0].humidity = 75.1;
    in.data.collections[1].temperature = 25.9;
    in.data.collections[1].mac = "ABCDE2";
    in.data.collections[1].humidity = 74.6;
    in.data.address = "DEFAB";
    std::string json = x2struct::X::tojson(in);
    std::cout<<json<<std::endl;
    return 0;
}

**Comment by HsiangCheng** [comment]
请问必须使用`O()`吗？我的同事使用`M()`好像会编译报错

**Comment by xyz347** [comment]
M也是可以的，O和M的不同在于解析json的时候。M包起来的字段必须存在。
比如O(a,b)可以解析{"a":1}，但是M(a,b)解析{"a":1}就会抛出异常，因为b不存在

**Comment by xyz347** [comment]
x@~$ ./xtest
{"errorCode":0,"message":"","data":{"timestamp":1531710826,"collections":[{"temperature":26.700000762939454,"mac":"ABCDEF","humidity":75.0999984741211},{"temperature":25.899999618530275,"mac":"ABCDE2","humidity":74.5999984741211}],"address":"DEFAB"}}
x@~$ ./xtest
{"errorCode":0,"message":"","data":{"timestamp":1531710826,"collections":[{"temperature":26.700000762939454,"mac":"ABCDEF","humidity":75.0999984741211},{"temperature":25.899999618530275,"mac":"ABCDE2","humidity":74.5999984741211}],"address":"DEFAB"}}

**Comment by xyz347** [comment]
O的运行结果
x@~$ ./xtest
{"errorCode":0,"message":"","data":{"timestamp":1531710826,"collections":[{"temperature":26.700000762939454,"mac":"ABCDEF","humidity":75.0999984741211},{"temperature":25.899999618530275,"mac":"ABCDE2","humidity":74.5999984741211}],"address":"DEFAB"}}

M的运行结果
x@~$ ./xtest
{"errorCode":0,"message":"","data":{"timestamp":1531710826,"collections":[{"temperature":26.700000762939454,"mac":"ABCDEF","humidity":75.0999984741211},{"temperature":25.899999618530275,"mac":"ABCDE2","humidity":74.5999984741211}],"address":"DEFAB"}}

**Comment by HsiangCheng** [comment]
抱歉，未能及时回复。我的同事还在调试代码中，你的回复对我们确定方向很有帮助，谢谢(*￣︶￣)
