### ISSUE TITLE
如何序列化 QMap

### ISSUE THREAD

**Issue by lhy0403** [xyz347/x2struct#11]
```
QMap <QString, QList<QString>> x;
x.insert("a", QList<QString>() << "content1" << "content2");
```
这个 QMap 无法转换成json

**Comment by xyz347** [comment]
Qt没用过，所以对于Qt的各种类型不了解。
如果Qt的QMap是基于std::map那是可以用的，你的例子里面可能是由于List的原因，目前暂时还没支持List。你试一下QMap<QString, QString>的序列化，如果可以，我再支持一下std::list

**Comment by lhy0403** [comment]
```
    QMap <QString, QString> x;
    x.insert("a", "x");
    x.insert("bbb", "adfvdf");
    auto mm = x2struct::X::tojson(x);
    cout << mm << endl;
```
这段代码编译出错，`x_struct_to_str` 未在范围内定义

**Comment by lhy0403** [comment]
建议支持 QList （或者叫 std::list ）

**Comment by xyz347** [comment]
我先支持std::list，Qt的我先了解一下。

**Comment by xyz347** [comment]
已经支持std::list

**Comment by lhy0403** [comment]
std::tuple 有没有在近期的考虑中？

**Comment by xyz347** [comment]
> std::tuple 有没有在近期的考虑中？

暂时没有考虑tuple。tuple的不定类型不好映射到json里面
