### ISSUE TITLE
Not able to Serialize Array of Struct

### ISSUE THREAD

**Issue by jaychanda** [xyz347/x2struct#13]
I want to serialize array of struct to json I.E. BestFive_copy Best5Sell[20]; Where BestFive_copy is my struct.I cannot use vector for some reason. Xtostruct is not able to serialize array of struct to json.

**Comment by xyz347** [comment]
use vector

**Comment by jaychanda** [comment]
I cannot use vector because I am unmarshalling struct at my end and it contains array of struct. Marshalling and unmarshalling cannot be done by vector. This is reason i have to rely on array.

**Comment by xyz347** [comment]
When you pass an array to a function, the array length information is lost. So can't support array
