### ISSUE TITLE
Failed to build with time_t on macOS

### ISSUE THREAD

**Issue by lhy0403** [xyz347/x2struct#24]
`time_t` is defined as these below in Linux:
```
time_t 
(in time_t.h) --> typedef __time_t time_t 
(in types.h) --> __STD_TYPE __TIME_T_TYPE __time_t; 
(in typesizes.h) --> #define __TIME_T_TYPE		__SYSCALL_SLONG_TYPE
```

and finally 

```
#if defined __x86_64__ && defined __ILP32__
# define __SYSCALL_SLONG_TYPE	__SQUAD_TYPE
# define __SYSCALL_ULONG_TYPE	__UQUAD_TYPE
#else
# define __SYSCALL_SLONG_TYPE	__SLONGWORD_TYPE
# define __SYSCALL_ULONG_TYPE	__ULONGWORD_TYPE
#endif
 ```

for different platforms.

--------------------

However, on macOS (at lease in macOS Catalina and 10.14), `time_t` is defined as long (from the compiler error message)...

Tl; Dr:
Seems that x2struct has a missing convert of type `long`， https://github.com/lhy0403/Qv2ray/commit/bcb328e772b50e7896e142450bd89dc9fcf939a0/checks?check_suite_id=379416319#step:6:321

**Comment by xyz347** [comment]
fixed, qt branch
