### ISSUE TITLE
不支持char

### ISSUE THREAD

**Issue by zhaobu** [xyz347/x2struct#3]
如果结构体里有char,就不支持了,该怎么改

**Comment by zhaobu** [comment]
报错.__x_to_struct”的左边必须有类/结构/联合

**Comment by xyz347** [comment]
> 如果结构体里有char,就不支持了,该怎么改

如果变量不需要进行json转换，相应的变量可以不放XTOSTRUCT里面去。
char在json好像也没有对应的类型。目前还不支持char []，如果是字符数组，建议用string

**Comment by zhaobu** [comment]
嗯嗯,明白了,谢谢.
