### ISSUE TITLE
not work on windows

### ISSUE THREAD

**Issue by EmileXVIII** [xyz347/x2struct#30]
error:
x2struct-master/xtypes.h:90:65: error: 'strptime' was not declared in this scope
         if (0 != strptime(str.c_str(), "%Y-%m-%d %H:%M:%S", &ttm)) {
                                                                 ^
fix used :
#if defined(\_\_WIN32\_\_)
#ifndef WINDOWS
#define WINDOWS
#endif

in order to fix it :
warn on README that you have to define WINDOWS on windows before importing the library

or

use \_\_WIN32\_\_ instead of WINDOWS

**Comment by xyz347** [comment]
This library will no longer be maintained, please go to [xpack](https://github.com/xyz347/xpack)
xpack support Windows
