### ISSUE TITLE
请问要如何重新实现struct::X::tojson这个函数

### ISSUE THREAD

**Issue by CasonTsai** [xyz347/x2struct#37]
非常感谢作者提供这么好的库，因为前端这块要求的json是多了个反斜杠的{\"aid\":\"1\",\"cid\":\"1\",\"cid_url\":\"11\",\"time_stamp\":\"1\",\"status\":\"1\",\"time_stamp\":\"1\",\"pic_name\":\"1\",\"pic_data\":\"\",\"data\":[{\"frame_id\":\"1\",\"time_stamp\":\"1\",\"alertFlag\":\"1\",\"headInfo\":[{\"x\":123,\"y\":123,\"width\":123,\"height\":123,\"numOfHelmet\":\"1\",\"color\":\"1\"}]}]}，但是这个库转json后是不带反斜杠的，请问如果有重新实现tojson这个函数要在哪里改

**Comment by xyz347** [comment]
是所有的双引号都要反斜杠吗？能否给个例子

**Comment by CasonTsai** [comment]
这个是x2struct 生成的json字符串
{\"aid\":\"1\",\"cid\":\"1\",\"cid_url\":\"11\",\"time_stamp\":\"1\",\"status\":\"1\",\"time_stamp\":\"1\",\"pic_name\":\"1\",\"pic_data\":\"\",\"data\":[{\"frame_id\":\"1\",\"time_stamp\":\"1\",\"alertFlag\":\"1\",\"headInfo\":[{\"x\":123,\"y\":123,\"width\":123,\"height\":123,\"numOfHelmet\":\"1\",\"color\":\"1\"}]}]}

下面这个是asp.net前端那块需要的格式
{\\\"aid\\\":\\\"1\\\",\\\"cid\\\":\\\"1\\\",\\\"cid_url\\\":\\\"11\\\",\\\"time_stamp\\\":\\\"1\\\",\\\"status\\\":\\\"1\\\",\\\"time_stamp\\\":\\\"1\\\",\\\"pic_name\\\":\\\"1\\\",\\\"pic_data\\\":\\\"\\\",\\\"data\\\":[{\\\"frame_id\\\":\\\"1\\\",\\\"time_stamp\\\":\\\"1\\\",\\\"alertFlag\\\":\\\"1\\\",\\\"headInfo\\\":[{\\\"x\\\":123,\\\"y\\\":123,\\\"width\\\":123,\\\"height\\\":123,\\\"numOfHelmet\\\":\\\"1\\\",\\\"color\\\":\\\"1\\\"}]}]}

**Comment by CasonTsai** [comment]
我好像找到了，可能要从rapidjson那里改，我试下，如果可以告诉您

**Comment by xyz347** [comment]
你试一下调用两次tojson，第一次把结构体转字符串，把转出来的字符串再tojson一次

**Comment by CasonTsai** [comment]
两种方法都可以哈哈，谢谢大佬
