### ISSUE TITLE
是否支持xml属性

### ISSUE THREAD

**Issue by TonyZhouTuo** [xyz347/x2struct#40]
您好，请问是否不支持 xml的属性字段

**Comment by xyz347** [comment]
读支持，写不支持

**Comment by TonyZhouTuo** [comment]
好的，谢谢
请问xml有没有类似你实现的其他库参考？

**Comment by xyz347** [comment]
x2struct不维护了，可以用xpack：https://github.com/xyz347/xpack#flag
用ATTR这个flag
