### ISSUE TITLE
需求:option变量转换到json，没有赋值时不会输出

### ISSUE THREAD

**Issue by andrewwang79** [xyz347/x2struct#43]
代码：
struct User
{
    int64_t id;
    string  name;
    string  mail;
    XTOSTRUCT(O(id, name, mail));
};

    User user;
    user.id = 1;
    user.name = "Jack";
    string json1 = x2struct::X::tojson(user);
    std::cout << json1 << std::endl;

当前输出结果：
{"id":1,"name":"Jack","mail":""}

期望输出结果：
{"id":1,"name":"Jack"}

**Comment by xyz347** [comment]
omitempty这个选项还不支持

**Comment by xyz347** [comment]
x2struct不维护了，可以用xpack：https://github.com/xyz347/xpack#flag
用OE这个flag
