### ISSUE TITLE
Not working with bool datatype

### ISSUE THREAD

**Issue by jaychanda** [xyz347/x2struct#9]
I am trying with bool datatype and i have also passed variable in optional field but xhas method returns 0 and when i evaluate the struct the bool variable contains numeric value..is there any issue with bool datatype?

**Comment by xyz347** [comment]
static bool loadjson(const std::string&str, TYPE&t, bool isfile=true, bool set_has=false);

if need use xhas, the last parameter(set_has) need to set true

**Comment by jaychanda** [comment]
if i don't pass bool variable in a json, then it assign some number to bool variable after loadjson method is called...it should assign default value as false for the bool variable.

**Comment by xyz347** [comment]
if number is not zero, assign true maybe better?

**Comment by xyz347** [comment]
latest version support numeric, not zero treat as true
